name: documentum
networks:
  documentum-network:
    driver: macvlan
    ipam:
      config: 
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.224/28
          gateway: 192.168.1.1
      options:
        parent: enp2s0

volumes:
  postgres-data:
  documentum-data:
  documentum-dba:
  documentum-config:
  documentum-apptoken:

services:
  postgres:
    image: postgres:12-alpine
    hostname: postgres
    container_name: postgres
    env_file:
      - .env
    networks:
      documentum-network:
        ipv4_address: 192.168.1.225
    volumes:
      - postgres-data:/var/lib/postgresql
  documentum:
    image: localhost:32000/dctm-cs:22.2
    hostname: documentum
    container_name: documentum
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "su", "-", "dmadmin", "-c", "bin/dm_health_check.sh"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 2m
    networks:
      documentum-network:
        ipv4_address: 192.168.1.226
    volumes:
      - ./documentum-data:/var/lib/documentum
      - ./documentum-dba:/opt/documentum/dba
      - ./documentum-config:/opt/documentum/config
      - ./documentum-dfcdata:/opt/documentum/dfcdata
      - ./documentum-presets:/opt/documentum/presets



